name: Build Docker Images (Auto-discover)

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}

jobs:
  detect-changed-services:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get list of changed services
        id: set-matrix
        run: |
          echo "🔎 Detecting changed services..."

          # Get list of changed top-level folders inside services/
          changed=$(git diff --name-only ${{ github.event.before }} ${{ github.event.base_ref }} | cut -d/ -f1 | uniq)

          echo "Changed services:"
          echo "$changed"

          matrix_entries="[]"

          for svc in $changed; do
            # Check if the svc actually has a Dockerfile
            if [ -f "$svc/Dockerfile" ]; then
              matrix_entries=$(jq -c --arg name "$svc" --arg path "$svc" '. + [{name: $name, path: $path}]' <<< "$matrix_entries")
            fi
          done

          echo "Detected matrix:"
          echo "$matrix_entries"

          echo "matrix=$matrix_entries" >> "$GITHUB_OUTPUT"

  build-and-push:
    runs-on: ubuntu-latest
    needs: detect-changed-services
    if: ${{ needs.detect-changed-services.outputs.matrix != '[]' }}
    strategy:
      matrix:
        svc: ${{ fromJson(needs.detect-changed-services.outputs.matrix) }}
    permissions:
      contents: read
      packages: write # Needed to push to GHCR
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{github.actor}}/${{ matrix.svc.name }}
          flavor: |
            latest=true

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64,linux/arm64
          context: ${{ matrix.svc.path }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}